#!/bin/bash
touch ~/.hushlogin

#sudo ln -s prats/pxy prats


# Initialize variables for summary
success_count=0
fail_count=0

# Common Setup
read -p "Are you sure you want to remove ~/prats? (y/n): " confirm
if [ "$confirm" = "y" ]; then
    if [ -d ~/prats ]; then
        sudo rm -rf ~/prats
        if [ $? -eq 0 ]; then
            echo -e "\e[32mRemoved ~/prats: Success\e[0m"
            ((success_count++))
        else
            echo -e "\e[31mFailed to remove ~/prats\e[0m"
            ((fail_count++))
            exit 1
        fi
    else
        echo "Directory ~/prats not found, moving on."
    fi

    sudo rm -rf /usr/local/bin/pxy*
    if [ $? -eq 0 ]; then
        echo -e "\e[32mRemoved files in /usr/local/bin/: Success\e[0m"
        ((success_count++))
    else
        echo -e "\e[31mFailed to remove files in /usr/local/bin/\e[0m"
        ((fail_count++))
        exit 1
    fi
fi

# User-specific Setup

current_user=$(whoami)

# User-specific Setup
usernames=("$current_user")
modified_successfully=false

for username in "${usernames[@]}"; do
    sudo usermod -aG sudo "$username"
    if [ $? -eq 0 ]; then
        echo -e "\e[32mUser modified successfully: $username\e[0m"
        ((success_count++))  # Increment success_count on successful user modification
        modified_successfully=true
        break  # Break out of loop on the first successful usermod
    else
        echo -e "\e[31mFailed to modify user: $username\e[0m"
    fi
done

# If modification was successful for any user, continue with the rest of the script
if [ "$modified_successfully" = true ]; then
    # apt-get upgrade
    sudo apt-get update
    sudo apt-get install multitail
    if [ $? -eq 0 ]; then
        echo -e "\e[32mapt-get upgrade successful\e[0m"
        ((success_count++))
    else
        echo -e "\e[31mapt-get upgrade failed\e[0m"
        ((fail_count++))
        exit 1
    fi

    # Git installation
    sudo apt-get install git
    if [ $? -eq 0 ]; then
        echo -e "\e[32mGit installation successful\e[0m"
        ((success_count++))
    else
        echo -e "\e[31mGit installation failed\e[0m"
        ((fail_count++))
        exit 1
    fi

    # Generate SSH key
    if [ -f ~/.ssh/id_rsa.pub ]; then
        echo "SSH key file already exists. Skipping key generation."
    else
        ssh-keygen -t rsa -b 4096 -C "parisharaghu@gmail.com"
        cat ~/.ssh/id_rsa.pub
    fi

    # Prompt for confirmation to proceed
    read -p "Do you want to proceed? (y/n): " confirm
    if [ "$confirm" != "y" ]; then
        echo "Exiting script."
        exit 0
    fi

    # git clone https://github.com/GitHubRaghu71/prats.git
    git clone git@github.com:GitHubRaghu71/prats.git
    if [ $? -eq 0 ]; then
        echo -e "\e[32mCloned prats repository successfully\e[0m"
        ((success_count++))
    else
        echo -e "\e[31mFailed to clone prats repository\e[0m"
        ((fail_count++))
        exit 1
    fi

    sudo chmod -R 777 prats
    if [ $? -eq 0 ]; then
        echo -e "\e[32mChanged permissions on prats directory: Success\e[0m"
        ((success_count++))
    else
        echo -e "\e[31mFailed to change permissions on prats directory\e[0m"
        ((fail_count++))
        exit 1
    fi

    sudo cp ~/prats/sys/pxy* /usr/local/bin/

    if [ $? -eq 0 ]; then
        echo -e "\e[32mCopied prats executables to /usr/local/bin/: Success\e[0m"
        ((success_count++))
    else
        echo -e "\e[31mFailed to copy prats executables to /usr/local/bin/\e[0m"
        ((fail_count++))
        exit 1
    fi

    sudo chmod +x /usr/local/bin/pxy*
    if [ $? -eq 0 ]; then
        echo -e "\e[32mChanged permissions on pxy executables: Success\e[0m"
        ((success_count++))
    else
        echo -e "\e[31mFailed to change permissions on pxy executables\e[0m"
        ((fail_count++))
        exit 1
    fi

    sudo apt-get install python3-venv
    if [ $? -eq 0 ]; then
        echo -e "\e[32mPython virtual environment installation successful\e[0m"
        ((success_count++))
    else
        echo -e "\e[31mPython virtual environment installation failed\e[0m"
        ((fail_count++))
        exit 1
    fi

    python3 -m venv myenv
    if [ $? -eq 0 ]; then
        echo -e "\e[32mPython virtual environment creation successful\e[0m"
        ((success_count++))
    else
        echo -e "\e[31mFailed to create Python virtual environment\e[0m"
        ((fail_count++))
        exit 1
    fi

    sudo chmod -R 777 myenv
    if [ $? -eq 0 ]; then
        echo -e "\e[32mChanged permissions on myenv directory: Success\e[0m"
        ((success_count++))
    else
        echo -e "\e[31mFailed to change permissions on myenv directory\e[0m"
        ((fail_count++))
        exit 1
    fi

    source ~/myenv/bin/activate
    sudo apt-get update
    sudo apt-get install python3-pip

    if [ $? -eq 0 ]; then
        echo -e "\e[32mUpgraded pip in virtual environment: Success\e[0m"
        ((success_count++))
    else
        echo -e "\e[31mFailed to upgrade pip in virtual environment\e[0m"
        ((fail_count++))
        exit 1
    fi

    # Install Python dependencies based on the current user
    if [ "$current_user" = "userland" ]; then
        # For userland user
        cd ~/prats
        source ~/myenv/bin/activate
        sudo pip install -r requirements.txt
    else
        # For other users, including "pxy"
        cd ~/prats
        source ~/myenv/bin/activate
        pip install -r requirements.txt
        #sudo ln -s ~/prats /prats
    fi
    
    # Check if installation was successful
    if [ $? -eq 0 ]; then
        echo -e "\e[32mInstalled Python dependencies: Success\e[0m"
        ((success_count++))
    else
        echo -e "\e[31mFailed to install Python dependencies\e[0m"
        ((fail_count++))
        exit 1
    fi
    sudo cp ~/prats/sys/.bashrc ~/.bashrc
    sudo apt-get install unzip
    cd ~/prats/sys/exe/run
    # Display summary at the end
    source ~/myenv/bin/activate
    pxypyc
    echo -e "\nSummary:"
    echo -e "\e[32mSuccesses: $success_count\e[0m"
    echo -e "\e[31mFailures: $fail_count\e[0m"
    
else
    echo -e "\nWas NOT successful. Exiting script."
    exit 1
fi

