#!/bin/bash

source ~/myenv/bin/activate

# Change to the script's directory
cd ~/prats/sys/exe/run

read -p "Press Enter to Check..."
python3 rmtknpxy.pyc
python3 loginpxy.pyc

# Run the Python scripts sequentially with prompts
read -p "Press Enter to run chkpxy.py..."
python3 chkpxy.pyc
